### ISSUE TITLE
Does Poseidon-Tensorflow support Multiple-GPU worker node?

### ISSUE THREAD

**Issue by christ115** [petuum-inc/poseidon-release#3]
Thank you for developing Poseidon, a very high performance distributed deep learning framework. 

I follow the steps in tutorials and run the "cifar10_train.py" successfully on our cluster (single GPU per machine). Indeed the speed-up ratio is nearly linear w.r.t. the number of nodes. 

Then I try the "cifar10_multi_gpu_train.py" in a similar way on another cluster in which each machine with 2-GPU Cards. Just spending a little effort I run this case successfully. And the shape of loss and accuracy curves seems correct. 

The question is: Dose Poseidon support the "Multiple-GPU per Machine" setting?

**Comment by xunzhang** [comment]
Yes. You can make use of multiple GPUs in one node to train.

From my iPhone
