### ISSUE TITLE
Program hangs when training a deep cnn with 200+ layers

### ISSUE THREAD

**Issue by christ115** [petuum-inc/poseidon-release#5]
I have trained many CNNs (<100 layers) by using Poseidon successfully on my cluster (4 machines, each has 2 GPUs).  

When I train a 200 layered ResNet in the same environments, the program hangs forever. The logs of server and worker nodes are as follows,

server:   I ./tensorflow/core/ps/ps_server.hpp:88] Initing id stage4/block41/conv1/weights/0
worker: I tensorflow/core/ps/ps_client.cpp:33] id: 239 key: stage4/block41/conv2/biases/0       bytes: 512

And seems the program always hangs in the same position. Could you give suggestions?

**Comment by xunzhang** [comment]
Hi, could you provide the training script and the cluster configuration file you use for us to reproduce this? Have you tried this with just one node, how many CPUs you have per node?

**Comment by christ115** [comment]
Hi, the training script and logs are attached.
[temp.zip](https://github.com/petuum-inc/poseidon-release/files/1265966/temp.zip)

I have 4 nodes. Each node has 2 GPUs and 2 CPUs (2x16 cores). Their OS are CentOS 7, Ubuntu 12.04, Ubuntu 14.04 and Ubuntu 14.04 respectively. All nodes are installed with CUDA 8 and CUDNN 5.

As your suggestion, I tried to run the script on each node.
1) When run 'python cifar10_multi_train.py', it works well on every node
2) When run 'psd_run -c config.json "python cifar10_multi_train.py"', it works well on CentOS 7 and  Ubuntu 12.04, but hangs on the other 2 nodes with Ubuntu 14.04.

I guess maybe the bug depends on the version of Operating System?
